version: "3.9"

services:
  mcp:
    build: .
    image: obsidian-mcp-server:dev
    environment:
      - VAULT_PATH=${VAULT_PATH:-/vault}
      - HOST=0.0.0.0
      - PORT=${PORT:-8765}
      - MCP_PATH=${MCP_PATH:-/mcp}
      # Optional DNS rebinding protection
      - MCP_ENABLE_DNS_PROTECT=${MCP_ENABLE_DNS_PROTECT:-false}
      - MCP_ALLOWED_HOSTS=${MCP_ALLOWED_HOSTS:-}
      - MCP_ALLOWED_ORIGINS=${MCP_ALLOWED_ORIGINS:-}
    ports:
      - "${PORT:-8765}:${PORT:-8765}"
    # When deploying, mount your vault at the same path as VAULT_PATH, e.g.:
    # volumes:
    #   - /path/on/host/or/remote/mount:/vault:ro
    #   - ./data:/data:rw  # For SQLite session persistence
    stdin_open: true
    tty: true
