services:
  mcp:
    build:
      context: .
      target: dev
    image: obsidian-mcp-server:dev
    environment:
      - VAULT_PATH=${VAULT_PATH:-/vault}
      - HOST=0.0.0.0
      - PORT=${PORT:-8765}
      - MCP_PATH=${MCP_PATH:-/mcp}
      # Optional DNS rebinding protection (disabled for local dev by default)
      - MCP_ENABLE_DNS_PROTECT=${MCP_ENABLE_DNS_PROTECT:-false}
      - MCP_ALLOWED_HOSTS=${MCP_ALLOWED_HOSTS:-}
      - MCP_ALLOWED_ORIGINS=${MCP_ALLOWED_ORIGINS:-}
      # OAuth 2.1 Authentication (optional)
      - AUTH_ENABLED=${AUTH_ENABLED:-false}
      - AUTH_PROVIDER=${AUTH_PROVIDER:-}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID:-}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET:-}
      - OAUTH_ISSUER=${OAUTH_ISSUER:-}
      - OAUTH_SCOPE=${OAUTH_SCOPE:-openid email profile}
      - OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI:-}
      - OAUTH_AUTHORIZATION_ENDPOINT=${OAUTH_AUTHORIZATION_ENDPOINT:-}
      - OAUTH_TOKEN_ENDPOINT=${OAUTH_TOKEN_ENDPOINT:-}
      - OAUTH_USERINFO_ENDPOINT=${OAUTH_USERINFO_ENDPOINT:-}
    ports:
      - "${PORT:-8765}:${PORT:-8765}"
    volumes:
      # Mount the project source for live reload
      - .:/app
      # Mount your local vault into the container at VAULT_PATH (read-only recommended)
      - ${HOST_VAULT:?Set HOST_VAULT to your local vault path}:${VAULT_PATH:-/vault}:rw
      # Mount data directory for SQLite session persistence
      - ./data:/data:rw
    # Ensure dependencies are present in the mounted workspace, then run watch mode
    command: ["sh", "-lc", "bun install && bun run dev:watch"]
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "node", "--enable-source-maps", "--loader", "ts-node/esm", "src/health.ts"]
      interval: 30s
      timeout: 5s
      retries: 3
