services:
  mcp:
    build: .
    image: obsidian-mcp-server:dev
    environment:
      - VAULT_PATH=${VAULT_PATH:-/vault}
      - HOST=0.0.0.0
      - PORT=${PORT:-8765}
      - MCP_PATH=${MCP_PATH:-/mcp}
      # Optional DNS rebinding protection (disabled for local dev by default)
      - MCP_ENABLE_DNS_PROTECT=${MCP_ENABLE_DNS_PROTECT:-false}
      - MCP_ALLOWED_HOSTS=${MCP_ALLOWED_HOSTS:-}
      - MCP_ALLOWED_ORIGINS=${MCP_ALLOWED_ORIGINS:-}
    ports:
      - "${PORT:-8765}:${PORT:-8765}"
    volumes:
      # Mount the project source for live reload
      - .:/app
      # Mount your local vault into the container at VAULT_PATH (read-only recommended)
      - ${HOST_VAULT:?Set HOST_VAULT to your local vault path}:${VAULT_PATH:-/vault}:rw
      # Mount data directory for SQLite session persistence
      - ./data:/data:rw
    # Ensure dependencies are present in the mounted workspace, then run watch mode
    command: ["sh", "-lc", "bun install && bun run dev:watch"]
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "node", "--enable-source-maps", "--loader", "ts-node/esm", "src/health.ts"]
      interval: 30s
      timeout: 5s
      retries: 3
