version: "3.9"

services:
  mcp:
    build: .
    image: obsidian-mcp-server:dev
    environment:
      - VAULT_PATH=${VAULT_PATH:-/vault}
      - HOST=0.0.0.0
      - PORT=${PORT:-8765}
      - MCP_PATH=${MCP_PATH:-/mcp}
      # Optional DNS rebinding protection
      - MCP_ENABLE_DNS_PROTECT=${MCP_ENABLE_DNS_PROTECT:-false}
      - MCP_ALLOWED_HOSTS=${MCP_ALLOWED_HOSTS:-}
      - MCP_ALLOWED_ORIGINS=${MCP_ALLOWED_ORIGINS:-}
      # OAuth 2.1 Authentication (optional)
      - AUTH_ENABLED=${AUTH_ENABLED:-false}
      - AUTH_PROVIDER=${AUTH_PROVIDER:-}
      - OAUTH_CLIENT_ID=${OAUTH_CLIENT_ID:-}
      - OAUTH_CLIENT_SECRET=${OAUTH_CLIENT_SECRET:-}
      - OAUTH_ISSUER=${OAUTH_ISSUER:-}
      - OAUTH_SCOPE=${OAUTH_SCOPE:-openid email profile}
      - OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI:-}
      - OAUTH_AUTHORIZATION_ENDPOINT=${OAUTH_AUTHORIZATION_ENDPOINT:-}
      - OAUTH_TOKEN_ENDPOINT=${OAUTH_TOKEN_ENDPOINT:-}
      - OAUTH_USERINFO_ENDPOINT=${OAUTH_USERINFO_ENDPOINT:-}
      - OAUTH_JWKS_URI=${OAUTH_JWKS_URI:-}
    ports:
      - "${PORT:-8765}:${PORT:-8765}"
    # When deploying, mount your vault at the same path as VAULT_PATH, e.g.:
    # volumes:
    #   - /path/on/host/or/remote/mount:/vault:ro
    #   - ./data:/data:rw  # For SQLite session persistence
    stdin_open: true
    tty: true
